version: '3'

services:
  backend:
    build: ./CoffeeShop-BackEnd
    ports:
      - "80:80"
      - "5001:5001"
    environment:
      - SERVER_HOST=0.0.0.0
      - DB_HOST=db.igeipovmzhkrroglguju.supabase.co
      - DB_USER=postgres
      - DB_PASSWORD=Bcarmen933!
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_SSL=true
      - PORT=80
      - WEBSOCKET_PORT=5001
      - JWT_SECRET=piratecafesecret

  frontend:
    build: ./CoffeeShop-FrontEnd
    ports:
      - "3000:80"
    environment:
      - VITE_API_HOST=piratecafe-backend.f0faedffgua6dsag.westeurope.azurecontainer.io
      - VITE_API_PORT=80
      - VITE_API_PROTOCOL=http
      - VITE_WEBSOCKET_PORT=80
      - VITE_WS_PROTOCOL=ws
    depends_on:
      - backend